server:
  port: 9000
spring:
  application:
    name: index12306-gateway${unique-name:}-service
  profiles:
#    active: aggregation
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 43.139.204.197:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
